import type { Metadata } from "next";
import { Wix_Madefor_Text } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import NextTopLoader from "nextjs-toploader";


const wixMadeforText = Wix_Madefor_Text({
  subsets: ["latin"],
  variable: "--font-wix-madefor-text",
  weight: ["400", "500", "600", "700", "800"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={cn("font-sans")}>
      <body className={`${wixMadeforText.className} overflow-hidden bg-[#0e0e0e] antialiased`}>
          <NextTopLoader color="#0B5CFF" height={3} showSpinner={false} />
        {children}
      </body>
    </html>
  );
}
